trigger:
  branches:
    include:
      - main

variables:
  COMPOSE_PROJECT_NAME: 'myapp'
  COMPOSE_FILE: 'docker-compose.yml'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Checkout
    jobs:
      - job: CheckoutRepo
        steps:
          - checkout: self

  - stage: Deploy
    jobs:
      - job: DockerComposeDeploy
        steps:
          - task: Bash@3
            name: DockerComposeDown
            displayName: 'Stop previous containers (if any)'
            inputs:
              targetType: 'inline'
              script: |
                docker compose down || true

          - task: Bash@3
            name: DockerComposePull
            displayName: 'Pull latest Docker images'
            inputs:
              targetType: 'inline'
              script: |
                docker compose pull

          - task: Bash@3
            name: DockerComposeUp
            displayName: 'Build and start containers'
            inputs:
              targetType: 'inline'
              script: |
                docker compose up -d --build
